create table public."Ores" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "Name" text not null,
  "Strength" integer null default 0,
  constraint Ores_pkey primary key (id),
  constraint Ores_Name_key unique ("Name")
) TABLESPACE pg_default;

